version: '2'
services:
  frontend:
    build: ./frontend
    expose:
      - "80"
  proxy:
    build: ./haproxy
    depends_on:
      - frontend
      - data
    ports:
      - "80:80"
  data:
    build: ./data
    expose:
      - "8080"
  frpc:
    build:
      context: ./frpc
    privileged: true
  balena-openssh:
    build:
      context: ./balena-openssh
    privileged: true